### ISSUE TITLE
Training Codes for Inception Network

### ISSUE THREAD

**Issue by zwandering** [matthias-wright/art-fid#11]
Would it be possible to share the code used for training the inception network? It would be very helpful!

My e-mail address is zhuhaokun@sjtu.edu.cn

Thanks very much!

**Comment by zwandering** [comment]
Hi, did you see this issue?

Would it be possible to share the code used for training the inception network? It would be very helpful!

My e-mail address is [zhuhaokun@sjtu.edu.cn](mailto:zhuhaokun@sjtu.edu.cn)

Thanks very much and thanks for your great work!

**Comment by matthias-wright** [comment]
Sorry for the late response. Unfortunately I don't have the training code anymore.
