### ISSUE TITLE
Different result with pytorch-fid (mseitzer)

### ISSUE THREAD

**Issue by KhanhNgoDuy** [matthias-wright/art-fid#15]
Hi, I am experiencing different result from your code and the code in [pytorch-fid](https://github.com/mseitzer/pytorch-fid).
Specifically, in my case, your code gives `FID = 5.0320`
while the other gives `FID = 56.6364` which is ~10 times larger than yours.

For both version, I'm replacing the `transforms=ToTensor()` with 

```
def test_transform():
    size = 512
    transform_list = []
    transform_list.append(transforms.Resize(size))
    transform_list.append(transforms.CenterCrop(size))
    transform_list.append(transforms.ToTensor())
    transform = transforms.Compose(transform_list)
    return transform
```

Is this an expected behavior?

**Comment by matthias-wright** [comment]
Yeah, this is expected. ArtFID and FID are two different metrics.

**Comment by KhanhNgoDuy** [comment]
Sorry for misleading you. I meant the calculation of `FID` value which is then used to compute `artFID` in your code has different result with the `pytorch-fid` repo.
