### ISSUE TITLE
Questions about ArtFID formula

### ISSUE THREAD

**Issue by BossunWang** [matthias-wright/art-fid#7]
Hi experts,
The e.q.2 is sum of LPIPS and FID_infinite.
1. LPIPS between content and stylized images more higher is better, but opposite on e.q.2.
ref: 
https://arxiv.org/pdf/2201.12543.pdf  
https://arxiv.org/pdf/2208.00921.pdf 
https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=9244092
https://arxiv.org/pdf/2006.01431.pdf

2. FID between style and stylized images is not good for distribution of holistic statistic.
something like context and structure difference from style and stylized images.
for example: stylized animal dataset and original style image from Monet
SIFID from SinGAN in which use single images pair distribution
https://arxiv.org/pdf/1905.01164.pdf
IS_infinite:  The Inception score is the expectation of KL divergence distance between two sets of generated images
https://arxiv.org/pdf/2006.01431.pdf

Do you have been some experiments about these two metric functions?

**Comment by matthias-wright** [comment]
Hi @BossunWang, thanks for reaching out! We haven't done any experiments about these metrics.
