### ISSUE TITLE
pip install art-fid is not working

### ISSUE THREAD

**Issue by 1211sh** [matthias-wright/art-fid#8]
Hi,
I tried "pip install art-fid" following your instruction, but it does not work. (screenshot uploaded)
Could you please check your version?
Thank you!

![image](https://user-images.githubusercontent.com/33894603/220267622-a7e7a8d9-fa28-4ec2-8e99-0755992d8f94.png)

**Comment by matthias-wright** [comment]
Hi @1211sh , it's working fine for me using Python 3.8 and pip 22.3.1. You probably need to upgrade your Python or pip version.
