### ISSUE TITLE
Inception network training code

### ISSUE THREAD

**Issue by ioannouE** [matthias-wright/art-fid#9]
Would it be possible to share the code used for training the Inception network? It would be really helpful.
Thank you in advance, and thank you for your contribution.

**Comment by matthias-wright** [comment]
Hi @ioannouE, I want to keep the training code separate from this repo because it is cleaner and easier to maintain that way. Give me an email address and I will send you the code.

**Comment by zwandering** [comment]
Would it be possible to share the code used for training the inception network? It would be very helpful!
My e-mail address is zhuhaokun@sjtu.edu.cn
Thanks very much!
